pipeline {
    agent any

    stages {
        stage('w/o docker') {
            steps {
                sh 'echo "Without docker"'
                sh 'touch container-no.txt'
            }
        }

        stage('Build') {
            agent {
                docker {
                    image 'golang:1.21-alpine'
                    reuseNode true
                    args '-v ${WORKSPACE}/.cache:/.cache'
                }
            }
            steps {
                dir('bugtracker-backend') {
                    sh '''
                        mkdir -p /.cache
                        chmod 777 /.cache
                        pwd
                        ls -la
                        go version
                        go build -o bugtracker-backend cmd/bugtracker/main.go
                    '''
                }
            }
        }
    }
}
